// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.API.Context;

#nullable disable

namespace OnlineShop.API.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20240604020206_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.API.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("946a0305-470a-461a-87e3-8fd62c6dc115"),
                            Name = "Електроніка"
                        },
                        new
                        {
                            Id = new Guid("a7a0b109-23ec-4af2-ad2c-4149a5888082"),
                            Name = "Книги"
                        },
                        new
                        {
                            Id = new Guid("96ccf359-94b9-4fad-a857-6fd2e4c6519f"),
                            Name = "Спорт та відпочинок"
                        });
                });

            modelBuilder.Entity("OnlineShop.API.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ShippingAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShippingAddressId")
                        .IsUnique();

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92daa1c6-86f9-43b6-9064-aa2b4c9958a8"),
                            CustomerEmail = "olexander@gmail.com",
                            CustomerName = "Olexander",
                            OrderDate = new DateTime(2024, 6, 4, 5, 2, 4, 932, DateTimeKind.Local).AddTicks(8414),
                            ShippingAddressId = new Guid("1c869fa4-7e41-4ef7-863f-d8cbdbdae30b")
                        },
                        new
                        {
                            Id = new Guid("d8c7bd81-a34c-4677-b698-dadac6708b84"),
                            CustomerEmail = "serhii@gmail.com",
                            CustomerName = "Serhii",
                            OrderDate = new DateTime(2024, 6, 4, 5, 2, 4, 932, DateTimeKind.Local).AddTicks(9091),
                            ShippingAddressId = new Guid("7128b902-4778-4a3d-975b-ab9c62e8a0c4")
                        });
                });

            modelBuilder.Entity("OnlineShop.API.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("51841a8b-5ba6-422f-a24f-ea1b36e9ee90"),
                            OrderId = new Guid("92daa1c6-86f9-43b6-9064-aa2b4c9958a8"),
                            ProductId = new Guid("bfeb5b61-d188-4074-8640-0fc5f24be7b3"),
                            Quantity = 1L
                        },
                        new
                        {
                            Id = new Guid("09299418-34de-47c4-bdb7-a1f4725e6a42"),
                            OrderId = new Guid("92daa1c6-86f9-43b6-9064-aa2b4c9958a8"),
                            ProductId = new Guid("95449600-d1eb-4377-b9fc-9dd70c0e4c50"),
                            Quantity = 1L
                        },
                        new
                        {
                            Id = new Guid("7a729c57-6a52-49bd-8418-a4a55362d3e7"),
                            OrderId = new Guid("d8c7bd81-a34c-4677-b698-dadac6708b84"),
                            ProductId = new Guid("cb1a499b-a1b6-4e94-95c9-d1dc4653f3a1"),
                            Quantity = 1L
                        });
                });

            modelBuilder.Entity("OnlineShop.API.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StockQuantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("16cdd060-3e1f-459e-9d5c-c69374dea2f8"),
                            CategoryId = new Guid("946a0305-470a-461a-87e3-8fd62c6dc115"),
                            Description = "Екран 16 IPS (1920x1200) WUXGA, матовий / AMD Ryzen 7 7730U (2.0 - 4.5 ГГц) / RAM 16 ГБ / SSD 512 ГБ / AMD Radeon Graphics / без ОД / Wi-Fi / Bluetooth / веб-камера / без ОС / 1.74 кг / сірий",
                            ImageUrl = "https://content.rozetka.com.ua/goods/images/big/334493611.jpg",
                            Name = "Ноутбук Lenovo IdeaPad Slim 3 16ABR8",
                            Price = 24530m,
                            StockQuantity = 10L
                        },
                        new
                        {
                            Id = new Guid("89cbcc94-afe6-4b6f-b959-c1dcf82b1e6a"),
                            CategoryId = new Guid("946a0305-470a-461a-87e3-8fd62c6dc115"),
                            Description = "Екран 15.6 IPS (1920x1080) Full HD, матовий / Intel Core i5-12450H (2.0 - 4.4 ГГц) / RAM 32 ГБ / SSD 512 ГБ / Intel Iris Xe Graphics / без ОД / LAN / Wi-Fi / Bluetooth / вебкамера / без ОС / 1.76 кг / сірий",
                            ImageUrl = "https://content1.rozetka.com.ua/goods/images/big/357248068.jpg",
                            Name = "Ноутбук Acer Aspire 5 A515-57-59NG",
                            Price = 26777m,
                            StockQuantity = 15L
                        },
                        new
                        {
                            Id = new Guid("bfeb5b61-d188-4074-8640-0fc5f24be7b3"),
                            CategoryId = new Guid("a7a0b109-23ec-4af2-ad2c-4149a5888082"),
                            Description = "Приготуйтеся до шторму, що сколихне увесь світ «Якщо все піде так, як я планував, то через тиждень, 30 серпня 2020 року, світ на хвилину затамує подих. На різних континентах відбуватимуться певні події, на перший погляд, ніяк не пов'язані. Тільки той, хто придивиться до них уважніше, зрозуміє, що насправді це фрагменти однієї й тієї ж історії».",
                            ImageUrl = "https://content2.rozetka.com.ua/goods/images/big/354966480.jpg",
                            Name = "Ідеальний шторм - Д. Райнгардт",
                            Price = 450.5m,
                            StockQuantity = 5L
                        },
                        new
                        {
                            Id = new Guid("95449600-d1eb-4377-b9fc-9dd70c0e4c50"),
                            CategoryId = new Guid("a7a0b109-23ec-4af2-ad2c-4149a5888082"),
                            Description = "Року Божого 1521 папа Лев Х видав буллу, в якій було сказано, що Рим ніколи не повинен залишатися в темряві. П’ять століть по тому негода призвела до збоїв у роботі однієї з електростанцій. Щоб усунути пошкодження, постачання електроенергії довелося відключити на добу. І Рим поглинула темрява, пробудивши зло.",
                            ImageUrl = "https://content2.rozetka.com.ua/goods/images/big/335210773.jpg",
                            Name = "Володар тіні - К. Донато",
                            Price = 240m,
                            StockQuantity = 3L
                        },
                        new
                        {
                            Id = new Guid("cb1a499b-a1b6-4e94-95c9-d1dc4653f3a1"),
                            CategoryId = new Guid("96ccf359-94b9-4fad-a857-6fd2e4c6519f"),
                            Description = "Мішок боксерський SportKo Бочонок PVC з кільцем 75 см черний - ідеальний варіант для домашнього використання.",
                            ImageUrl = "https://content1.rozetka.com.ua/goods/images/big/220901139.png",
                            Name = "Мішок боксерський Sportko Бочечка",
                            Price = 1175m,
                            StockQuantity = 7L
                        });
                });

            modelBuilder.Entity("OnlineShop.API.Entities.ShippingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("HouseNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShippingAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c869fa4-7e41-4ef7-863f-d8cbdbdae30b"),
                            City = "Київ",
                            Country = "Україна",
                            HouseNumber = 11L,
                            OrderId = new Guid("92daa1c6-86f9-43b6-9064-aa2b4c9958a8"),
                            Street = "Хрещатик"
                        },
                        new
                        {
                            Id = new Guid("7128b902-4778-4a3d-975b-ab9c62e8a0c4"),
                            City = "Кропивницький",
                            Country = "Україна",
                            HouseNumber = 8L,
                            OrderId = new Guid("d8c7bd81-a34c-4677-b698-dadac6708b84"),
                            Street = "Соборна"
                        });
                });

            modelBuilder.Entity("OnlineShop.API.Entities.Order", b =>
                {
                    b.HasOne("OnlineShop.API.Entities.ShippingAddress", "ShippingAddress")
                        .WithOne("Order")
                        .HasForeignKey("OnlineShop.API.Entities.Order", "ShippingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("OnlineShop.API.Entities.OrderItem", b =>
                {
                    b.HasOne("OnlineShop.API.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.API.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.API.Entities.Product", b =>
                {
                    b.HasOne("OnlineShop.API.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineShop.API.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineShop.API.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OnlineShop.API.Entities.ShippingAddress", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
