// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.DAL.Context;

#nullable disable

namespace OnlineStore.DAL.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.DAL.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b39"),
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Name = "Smartphones",
                            ParentCategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b39")
                        },
                        new
                        {
                            Id = new Guid("b1a2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Name = "Apple",
                            ParentCategoryId = new Guid("a1b2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("91a2b3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Name = "Samsung",
                            ParentCategoryId = new Guid("a1b2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("91a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Name = "Gadgets",
                            ParentCategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b39")
                        },
                        new
                        {
                            Id = new Guid("71a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Name = "Smartwatches",
                            ParentCategoryId = new Guid("91a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("81a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Name = "Fitness Trackers",
                            ParentCategoryId = new Guid("91a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a")
                        },
                        new
                        {
                            Id = new Guid("6f319f69-85dd-4923-ac9f-5acd0b2a1b39"),
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b40"),
                            Name = "Men's Clothing",
                            ParentCategoryId = new Guid("6f319f69-85dd-4923-ac9f-5acd0b2a1b39")
                        },
                        new
                        {
                            Id = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b41"),
                            Name = "Women's Clothing",
                            ParentCategoryId = new Guid("6f319f69-85dd-4923-ac9f-5acd0b2a1b39")
                        },
                        new
                        {
                            Id = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b42"),
                            Name = "Kids' Clothing",
                            ParentCategoryId = new Guid("6f319f69-85dd-4923-ac9f-5acd0b2a1b39")
                        });
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreviewImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d83b8d3d-03f6-4975-b6f4-4b2c7791468d"),
                            CategoryId = new Guid("b1a2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "Screen (6.1\", IPS (Liquid Retina HD), 1792x828) / Apple A13 Bionic / main dual camera: 12 MP + 12 MP, front camera: 12 MP / RAM 4 GB / 128 GB built-in memory / 3G / LTE / GPS / GLONASS / Nano-SIM / iOS 13 / 3046 mAh",
                            PreviewImage = "https://content.rozetka.com.ua/goods/images/big_tile/37399227.png",
                            Price = 564.14m,
                            Rating = 4,
                            Title = "Mobile phone Apple iPhone 11 128GB Black"
                        },
                        new
                        {
                            Id = new Guid("79a8b7b1-5b5c-4096-bf59-2f5d491949d9"),
                            CategoryId = new Guid("b1a2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "Screen (6.7\", OLED (Super Retina XDR), 2796x1290) / Apple A17 Pro / main triple camera: 48 MP + 12 MP + 12 MP, front camera: 12 MP / 256 GB of built-in memory / 3G / LTE / 5G / GPS / Nano-SIM / iOS 17",
                            PreviewImage = "https://content1.rozetka.com.ua/goods/images/big_tile/364834251.jpg",
                            Price = 1436.04m,
                            Rating = 5,
                            Title = "Mobile phone Apple iPhone 15 Pro Max 256GB Natural Titanium"
                        },
                        new
                        {
                            Id = new Guid("6d526229-d129-4b10-b671-949942b64645"),
                            CategoryId = new Guid("b1a2c3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "Screen (6.1\", OLED (Super Retina XDR), 2532x1170) / Apple A15 Bionic / dual main camera: 12 MP + 12 MP, front camera: 12 MP / 128 GB of built-in memory / 3G / LTE / 5G / GPS / Nano-SIM, eSIM / iOS 15",
                            PreviewImage = "https://content1.rozetka.com.ua/goods/images/big_tile/221027910.jpg",
                            Price = 692.34m,
                            Rating = 4,
                            Title = "Mobile phone Apple iPhone 13 128GB Starlight"
                        },
                        new
                        {
                            Id = new Guid("f4a17b45-d6f6-4922-80a1-8cb09ac6958c"),
                            CategoryId = new Guid("91a2b3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "Screen (6.5\", Super AMOLED, 2340x1080) / Mediatek Helio G99 (2 x 2.6 GHz + 6 x 2.0 GHz) / main triple camera: 50 MP + 5 MP + 2 MP, front camera: 13 MP / RAM 6 GB / 128 GB of built-in memory + microSD (up to 1 TB) / 3G / LTE / GPS / GLONASS / BDS / support for 2 SIM cards (Nano-SIM) / Android 13 / 5000 mAh",
                            PreviewImage = "https://content.rozetka.com.ua/goods/images/big_tile/328132326.jpg",
                            Price = 194.87m,
                            Rating = 3,
                            Title = "Mobile phone Samsung Galaxy A24 6/128GB Black"
                        },
                        new
                        {
                            Id = new Guid("b7df95a3-c2bc-4c3a-91bb-d92776959bd7"),
                            CategoryId = new Guid("91a2b3d4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "Screen (6.8\", Dynamic AMOLED 2X, 3088x1440) / Qualcomm Snapdragon 8 Gen 2 for Galaxy (3.36 GHz + 2.8 GHz + 2.8 GHz + 2.0 GHz) / main quad camera: 10 MP front 12 MP / RAM 12 GB / 256 GB built-in memory / 3G / LTE / 5G / GPS / support for 2x SIM-cards (Nano-SIM) / Android 13 / 5000 mAh * h",
                            PreviewImage = "https://content2.rozetka.com.ua/goods/images/big_tile/310655416.jpg",
                            Price = 692.34m,
                            Rating = 4,
                            Title = "Mobile phone Samsung Galaxy S23 Ultra 12/256GB Beige"
                        },
                        new
                        {
                            Id = new Guid("c67c49f3-71cf-4a3f-89b0-0056fbcb1107"),
                            CategoryId = new Guid("71a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "Your important companions are now even more powerful. Accident detection to get help in an emergency. Stages of sleep to better understand your sleep. As well as new ways to train with the enhanced Workout app. The future of healthcare has never looked so good.",
                            PreviewImage = "https://content.rozetka.com.ua/goods/images/big_tile/364852941.jpg",
                            Price = 282.06m,
                            Rating = 5,
                            Title = "Apple Watch SE (2023) GPS 40mm Starlight Aluminum Case with Starlight Sport Band - S/M"
                        },
                        new
                        {
                            Id = new Guid("3b1b1bb2-655f-4689-8d88-70f9792dc842"),
                            CategoryId = new Guid("71a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "The watch that knows everything about you returns with a personalized fitness interface and improved sleep tracking. Galaxy Watch6 now features Sleep Tips to help you start your day with a good night's sleep.",
                            PreviewImage = "https://content1.rozetka.com.ua/goods/images/big_tile/353760040.jpg",
                            Price = 261.54m,
                            Rating = 3,
                            Title = "Smart watch Samsung Galaxy Watch 6 44mm Black"
                        },
                        new
                        {
                            Id = new Guid("04c13a1a-2324-4d5c-aa54-20c2a07a0a8b"),
                            CategoryId = new Guid("81a2b3c4-95f6-4d3c-8b7a-6f594d3c2b1a"),
                            Description = "The gadget provides accurate monitoring based on a two-channel module. Blood oxygen level control has become 10% more accurate. With its help, you can monitor a dozen of user health parameters: from heart rate to sleep quality. Going to training? You can record an activity track without using a smartphone. In basic mode, the device works for 14 days. The voice assistant makes it possible to use the functionality of the device to the maximum.",
                            PreviewImage = "https://content2.rozetka.com.ua/goods/images/big_tile/412885387.jpg",
                            Price = 76.91m,
                            Rating = 4,
                            Title = "Fitness bracelet Xiaomi Mi Smart Band 8 Pro Black"
                        },
                        new
                        {
                            Id = new Guid("b9a06fd0-9d17-4901-b998-7b193980f1fd"),
                            CategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b41"),
                            Description = "Go retro and modern with this Nike W Nsw Air Oos Flc Crew Sweatshirt. Soft and pleasant to the touch fabric of medium density provides breathability, so it can be worn all year round. The loose fit and dropped shoulder line enhance the bold and carefree vibe.",
                            PreviewImage = "https://content2.rozetka.com.ua/goods/images/big_tile/398539813.jpg",
                            Price = 107.45m,
                            Rating = 5,
                            Title = "Oversized Women's Nike Air Fleece Crew Sweatshirt FN1897-675 S Playful Pink/Photon Dust"
                        },
                        new
                        {
                            Id = new Guid("f89271d8-92d4-4d4a-9142-0919908307a3"),
                            CategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b41"),
                            Description = "Copper coat with a slit. Fastens with hidden buttons, has a belt. Raglan sleeve. The coat has laconic pockets.",
                            PreviewImage = "https://content2.rozetka.com.ua/goods/images/big_tile/365162840.jpg",
                            Price = 86.93m,
                            Rating = 4,
                            Title = "Women's autumn long coat OZZE D363-1 48 Milk"
                        },
                        new
                        {
                            Id = new Guid("5a3bb2f4-5b89-46c5-9d15-d3d05c4f3886"),
                            CategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b40"),
                            Description = "The Columbia Silver Falls Hooded Jacket is a versatile and comfortable layer at any time of the year. Synthetic insulation provides warmth without weight, and the jacket folds into its own pocket, perfect for travel.",
                            PreviewImage = "https://content1.rozetka.com.ua/goods/images/big_tile/371935662.jpg",
                            Price = 78.27m,
                            Rating = 5,
                            Title = "Demi-season hooded jacket for men Columbia Silver Falls Hooded Jacket 2034501-023 M Gray"
                        },
                        new
                        {
                            Id = new Guid("29f11039-71f6-47ab-b498-2cbf9c1c28aa"),
                            CategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b40"),
                            Description = "Men's demi-season jacket s.Oliver is a stylish combination of comfort and practicality. Mid-length and with a zipper, it will easily fit into your everyday look. Two side pockets and an additional zip pocket on the chest make this jacket not only fashionable but also functional. A simple and secure zip closure provides extra comfort on chilly days.",
                            PreviewImage = "https://content1.rozetka.com.ua/goods/images/big_tile/394186890.jpg",
                            Price = 82.04m,
                            Rating = 3,
                            Title = "Men's demi-season jacket s.Oliver 10.3.11.16.160.2140534-7450 2XL Green"
                        },
                        new
                        {
                            Id = new Guid("03223da7-6b63-4d52-a84d-2cb9ac560af7"),
                            CategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b42"),
                            Description = "Membrane trekking jacket for boys from 4F. The model is made of technical material with a hydrophobic coating. The NeoDry 5000/3000 membrane is used, which is supplemented with taped critical seams. They will protect against moisture absorption during light rainfall. The jacket will also work well in urban environments.",
                            PreviewImage = "https://content.rozetka.com.ua/goods/images/big_tile/358606821.jpg",
                            Price = 49.72m,
                            Rating = 5,
                            Title = "Teenage demi-season jacket for boy 164 cm Khaki"
                        },
                        new
                        {
                            Id = new Guid("c2f34b8c-446d-4917-8d84-b575ca0d5a4d"),
                            CategoryId = new Guid("7f319f69-85dd-4923-ac9f-5acd0b2a1b42"),
                            Description = "This oversized sweatshirt from Nike has plenty of arm and body room, so you'll always feel comfortable and relaxed wherever you are. Smooth on the outside and soft on the inside, this lightweight fleece is great when you need a little extra warmth. An embroidered Futura logo on the chest gives this crew neck a signature Club Fleece look.",
                            PreviewImage = "https://content1.rozetka.com.ua/goods/images/big_tile/419197501.jpg",
                            Price = 55.11m,
                            Rating = 4,
                            Title = "Children's sweatshirt for girls Nike G Nsw Flc Ovrszd Crew Lbr XS 122-128 cm Adobe/White"
                        });
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6aa41a29-1b0a-4079-8909-caeecb0e3f96"),
                            ProductId = new Guid("d83b8d3d-03f6-4975-b6f4-4b2c7791468d"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/37399230.jpg"
                        },
                        new
                        {
                            Id = new Guid("ccb7a96e-4d41-41b1-a9ff-2074fbe2ddd3"),
                            ProductId = new Guid("d83b8d3d-03f6-4975-b6f4-4b2c7791468d"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/37399239.jpg"
                        },
                        new
                        {
                            Id = new Guid("0df75f54-fe77-4ab2-bcdc-37dd73d93e2b"),
                            ProductId = new Guid("d83b8d3d-03f6-4975-b6f4-4b2c7791468d"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/37399245.jpg"
                        },
                        new
                        {
                            Id = new Guid("167d55d6-b68a-4ba3-9cc9-5aa96393995b"),
                            ProductId = new Guid("79a8b7b1-5b5c-4096-bf59-2f5d491949d9"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/364834253.jpg"
                        },
                        new
                        {
                            Id = new Guid("5c656d28-c364-4e12-a15d-a4ee1ac7b465"),
                            ProductId = new Guid("79a8b7b1-5b5c-4096-bf59-2f5d491949d9"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/364834255.jpg"
                        },
                        new
                        {
                            Id = new Guid("f864c55a-be78-466a-8b0c-168770820b16"),
                            ProductId = new Guid("79a8b7b1-5b5c-4096-bf59-2f5d491949d9"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/364834254.jpg"
                        },
                        new
                        {
                            Id = new Guid("bb568a43-8627-4547-b692-a4655a3eae5f"),
                            ProductId = new Guid("6d526229-d129-4b10-b671-949942b64645"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/221214136.jpg"
                        },
                        new
                        {
                            Id = new Guid("0675d8c8-3053-4176-a4c2-1aa57f0e4c23"),
                            ProductId = new Guid("6d526229-d129-4b10-b671-949942b64645"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/221214137.jpg"
                        },
                        new
                        {
                            Id = new Guid("a66b0ce5-3410-4738-ac4d-3d5ea3436e79"),
                            ProductId = new Guid("6d526229-d129-4b10-b671-949942b64645"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/221214138.jpg"
                        },
                        new
                        {
                            Id = new Guid("c4dd2c0d-426d-423a-93f6-4636ea6267d6"),
                            ProductId = new Guid("f4a17b45-d6f6-4922-80a1-8cb09ac6958c"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/328132329.jpg"
                        },
                        new
                        {
                            Id = new Guid("4a876fa4-2936-4954-8522-1f556ba8d2d3"),
                            ProductId = new Guid("f4a17b45-d6f6-4922-80a1-8cb09ac6958c"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/328132330.jpg"
                        },
                        new
                        {
                            Id = new Guid("9f0ea046-19b3-4925-9484-b233b22b973d"),
                            ProductId = new Guid("f4a17b45-d6f6-4922-80a1-8cb09ac6958c"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/328132333.jpg"
                        },
                        new
                        {
                            Id = new Guid("b9b2a6d2-49f0-40e0-9068-162ceff10859"),
                            ProductId = new Guid("b7df95a3-c2bc-4c3a-91bb-d92776959bd7"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/310655416.jpg"
                        },
                        new
                        {
                            Id = new Guid("6c8f297c-4c93-46a8-b364-4144a9cf5f57"),
                            ProductId = new Guid("b7df95a3-c2bc-4c3a-91bb-d92776959bd7"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/310655419.jpg"
                        },
                        new
                        {
                            Id = new Guid("32192e6f-d487-4fc6-998b-587fd3d566b6"),
                            ProductId = new Guid("b7df95a3-c2bc-4c3a-91bb-d92776959bd7"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/310655427.jpg"
                        },
                        new
                        {
                            Id = new Guid("15bd5fae-aadb-4ef2-8f51-206aceb3bf64"),
                            ProductId = new Guid("c67c49f3-71cf-4a3f-89b0-0056fbcb1107"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/364852941.jpg"
                        },
                        new
                        {
                            Id = new Guid("18f9d627-3127-491d-9623-442177c0376b"),
                            ProductId = new Guid("c67c49f3-71cf-4a3f-89b0-0056fbcb1107"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/364852943.jpg"
                        },
                        new
                        {
                            Id = new Guid("1ae2053f-1da3-4f24-abdb-bbd73a274bcb"),
                            ProductId = new Guid("3b1b1bb2-655f-4689-8d88-70f9792dc842"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/353760041.jpg"
                        },
                        new
                        {
                            Id = new Guid("8d4623dd-843c-4500-94a2-3486fd823e64"),
                            ProductId = new Guid("3b1b1bb2-655f-4689-8d88-70f9792dc842"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/353760042.jpg"
                        },
                        new
                        {
                            Id = new Guid("1d017eb3-1c3f-482a-9d73-5960f47d820b"),
                            ProductId = new Guid("3b1b1bb2-655f-4689-8d88-70f9792dc842"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/353760043.jpg"
                        },
                        new
                        {
                            Id = new Guid("0a4391d2-92fd-4ebc-8b52-b7a3aec66dda"),
                            ProductId = new Guid("04c13a1a-2324-4d5c-aa54-20c2a07a0a8b"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/412885389.jpg"
                        },
                        new
                        {
                            Id = new Guid("69eaf83f-1281-44f5-89f7-7edddccf7659"),
                            ProductId = new Guid("04c13a1a-2324-4d5c-aa54-20c2a07a0a8b"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/412885391.jpg"
                        },
                        new
                        {
                            Id = new Guid("930d38be-17dd-40a3-9c01-de9bf4682790"),
                            ProductId = new Guid("04c13a1a-2324-4d5c-aa54-20c2a07a0a8b"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/412885394.jpg"
                        },
                        new
                        {
                            Id = new Guid("dd1f37d6-a98a-434c-9a4d-194019f05e06"),
                            ProductId = new Guid("04c13a1a-2324-4d5c-aa54-20c2a07a0a8b"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/412885396.jpg"
                        },
                        new
                        {
                            Id = new Guid("0071eea5-840f-40fa-b52f-aeabeeb1ada1"),
                            ProductId = new Guid("b9a06fd0-9d17-4901-b998-7b193980f1fd"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/398539813.jpg"
                        },
                        new
                        {
                            Id = new Guid("09567c32-967d-49a1-852a-e4175fd8426e"),
                            ProductId = new Guid("b9a06fd0-9d17-4901-b998-7b193980f1fd"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/398539816.jpg"
                        },
                        new
                        {
                            Id = new Guid("fe0989ed-1f66-4907-9aad-084e574c7e81"),
                            ProductId = new Guid("f89271d8-92d4-4d4a-9142-0919908307a3"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/365162840.jpg"
                        },
                        new
                        {
                            Id = new Guid("add4b8a2-8edd-4905-999a-fc4ef8e52f08"),
                            ProductId = new Guid("f89271d8-92d4-4d4a-9142-0919908307a3"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/365162842.jpg"
                        },
                        new
                        {
                            Id = new Guid("fc7d9af0-7947-49fa-8e2d-fda5e0f49d44"),
                            ProductId = new Guid("f89271d8-92d4-4d4a-9142-0919908307a3"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/365162844.jpg"
                        },
                        new
                        {
                            Id = new Guid("ef60e5c5-78e5-44fa-bac3-3636f00a21c8"),
                            ProductId = new Guid("5a3bb2f4-5b89-46c5-9d15-d3d05c4f3886"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/371935662.jpg"
                        },
                        new
                        {
                            Id = new Guid("c9d46444-4106-4255-b44c-8ce1391b659c"),
                            ProductId = new Guid("5a3bb2f4-5b89-46c5-9d15-d3d05c4f3886"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/371935667.jpg"
                        },
                        new
                        {
                            Id = new Guid("753b7800-f508-4202-ae39-01469bbd0a8b"),
                            ProductId = new Guid("5a3bb2f4-5b89-46c5-9d15-d3d05c4f3886"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/371935679.jpg"
                        },
                        new
                        {
                            Id = new Guid("ef20dc91-c7f8-42bc-8e43-0c86a340838a"),
                            ProductId = new Guid("29f11039-71f6-47ab-b498-2cbf9c1c28aa"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/394186890.jpg"
                        },
                        new
                        {
                            Id = new Guid("09a90b9f-6ad2-48a7-9fd7-86e57db2dc35"),
                            ProductId = new Guid("29f11039-71f6-47ab-b498-2cbf9c1c28aa"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/394186893.jpg"
                        },
                        new
                        {
                            Id = new Guid("a4139af2-e9cf-4473-97c5-49b1b8bd5199"),
                            ProductId = new Guid("29f11039-71f6-47ab-b498-2cbf9c1c28aa"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/394186900.jpg"
                        },
                        new
                        {
                            Id = new Guid("48d8c4e4-d4a6-4cb0-8818-0ecff110782b"),
                            ProductId = new Guid("03223da7-6b63-4d52-a84d-2cb9ac560af7"),
                            Url = "https://content.rozetka.com.ua/goods/images/big/358606821.jpg"
                        },
                        new
                        {
                            Id = new Guid("b339980d-73fe-4392-93b0-a62f09a7e5dd"),
                            ProductId = new Guid("03223da7-6b63-4d52-a84d-2cb9ac560af7"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/358606827.jpg"
                        },
                        new
                        {
                            Id = new Guid("613f38e4-68c3-48d0-bb8f-a4c46ef25022"),
                            ProductId = new Guid("03223da7-6b63-4d52-a84d-2cb9ac560af7"),
                            Url = "https://content2.rozetka.com.ua/goods/images/big/358606835.jpg"
                        },
                        new
                        {
                            Id = new Guid("b6ac62fb-2a15-4715-9aef-8ae24d42be64"),
                            ProductId = new Guid("c2f34b8c-446d-4917-8d84-b575ca0d5a4d"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/419197501.jpg"
                        },
                        new
                        {
                            Id = new Guid("eedafee0-9371-4d97-9766-f25d9ef7b9c7"),
                            ProductId = new Guid("c2f34b8c-446d-4917-8d84-b575ca0d5a4d"),
                            Url = "https://content1.rozetka.com.ua/goods/images/big/419197503.jpg"
                        });
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Category", b =>
                {
                    b.HasOne("OnlineStore.DAL.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Product", b =>
                {
                    b.HasOne("OnlineStore.DAL.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.ProductImage", b =>
                {
                    b.HasOne("OnlineStore.DAL.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Review", b =>
                {
                    b.HasOne("OnlineStore.DAL.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineStore.DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("OnlineStore.DAL.Entities.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
